[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "

[[battery.display]]
threshold = 40

[cmd_duration]
format = "· [$duration]($style) "

[git_branch]
format = "· [$symbol$branch]($style) "

[nodejs]
format = "· [$symbol$version]($style) "
symbol = "⬢ "

[package]
format = "· [$symbol$version]($style) "
display_private = true

[php]
format = "· [$symbol$version]($style) "
