# https://github.com/Coffee2CodeNL/gebaar-libinput
# Install 'xdotool' and 'wmctrl'

[commands.swipe.three]
left_up = ""
right_up = ""
up = "xdotool key ctrl+F9"
left_down = ""
right_down = ""
down = "xdotool key ctrl+F9"
left = "wmctrl -s 1"
right = "wmctrl -s 0"

[commands.swipe.four]
left_up = ""
right_up = ""
up = "wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz"
left_down = ""
right_down = ""
down = "wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz"
left = "xdotool key alt+Right"
right = "xdotool key alt+Left"
